
package soap_client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AccountDoesNotExistException", targetNamespace = "http://service/")
public class AccountDoesNotExistFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AccountDoesNotExistException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AccountDoesNotExistFault(String message, AccountDoesNotExistException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AccountDoesNotExistFault(String message, AccountDoesNotExistException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap_client.AccountDoesNotExistException
     */
    public AccountDoesNotExistException getFaultInfo() {
        return faultInfo;
    }

}
