
package soap_client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidAccountParameterException", targetNamespace = "http://service/")
public class InvalidAccountParameterFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidAccountParameterException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidAccountParameterFault(String message, InvalidAccountParameterException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidAccountParameterFault(String message, InvalidAccountParameterException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: soap_client.InvalidAccountParameterException
     */
    public InvalidAccountParameterException getFaultInfo() {
        return faultInfo;
    }

}
